### ISSUE TITLE
Adding svg and jpg/png as possible outputs

### ISSUE THREAD

**Issue by ruzickap** [tueda/makefile4latex#10]
Hello.

Would it be possible to ass the `svg` and `png` as outputs?

I'm using this command to get `svg` from the `tex`:

```bash
latex ${FILE}.tex
dvisvgm -n ${FILE}.dvi
```

It may be also handy to get the "png / jpg" output as well:

```bash
pdflatex ${FILE}.tex
pdftoppm -singlefile -jpeg -r 200 ${FILE}.pdf ${FILE}
# or
pdftoppm -singlefile -png -r 200 ${FILE}.pdf ${FILE}
```

I'm using it for generating the cheatsheets like:
https://github.com/ruzickap/cheatsheet-atom

Thank you...

**Comment by tueda** [comment]
Thank you for your suggestion. I put `svg`, `jpg`, `png` rules into the Makefile, so you can use
```shell
make svg
make jpg
make png
```

For now, I'm using `dvisvgm` for .svg files as you suggested. Indeed this has the advantage that it is included in TeX Live. But I'm not sure if it is best from the viewpoint of quality; `pdf2svg`, `pdftocairo` or `mudraw` may be used as a `pdf` -> `svg` converter. This may be changed in future.

For `jpg`/`png` outputs, I do not like to fix the image resolution to any value, because it really depends on one's purpose. If the default value is not good for you, then you can change it by `PDFTOPPM_OPT` (or `PDFTOPPM_JPG_OPT`/`PDFTOPPM_PNG_OPT`) in the user customization file `.latex.mk`:
```shell
echo 'PDFTOPPM_OPT += -r 200' >>.latex.mk
```

**Comment by ruzickap** [comment]
Awesome thanks a lot. It's working fine :-)
